일본어를 추가하였습니다.
techinpark/appstore-status-bot pull request #9
Opened 2022-01-26 04:55 UTC by RyuuseiKang

일본어를 추가하였습니다.

2022-01-26 15:42 UTC, techinpark requested changes
@RyuuseiKang 일본어 기여해주셔서 감사합니다! 

다국어 지원을 추가하려면 https://github.com/techinpark/appstore-status-bot/blob/3cadf95023d72f56df345516407c4aeadad18e7d/Sources/slack.js#L11 

해당 라인에 일본어 관련 정보를 넣어주어야하는데 해당부분 한번 확인 부탁드릴게요!

2022-01-26 15:42 UTC, techinpark commented on locales/ja.json
> +	"Processing for App Store": "App Store 판매 준비중",
`판매 준비중` 이라는 단어도 일본어로 들어가면 좋을 것 같습니다!

2022-01-26 15:42 UTC, techinpark commented on README-JAPANESE.md
> +<img src="./.github/images/preview_ko.png" width="70%">
`preview_ko.png` 이미지를 사용해주셨는데 별도의 일본어로된 스크린샷 혹은 영문 이미지를 이용하는건 어떨까요?

2022-01-27 06:30 UTC, RyuuseiKang commented
추가 반영하였습니다! 감사합니다!

2022-01-28 00:46 UTC, merged